# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  workflow_dispatch:

env:
  env_var: ${{ vars.ENV_CONTEXT_VAR }}
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ vars.ENVIRONMENT_STAGE }}

    steps:
    - uses: actions/checkout@v3
      with:
         ROOT_PASSWORD: ${{ secrets.ROOT_PASSWORD }}
      env:
         ROOT_PASSWORD: ${{ secrets.ROOT_PASSWORD }}
         
    - name: Configure CMake
      run: |
        printf "%s" ${ROOT_PASSWORD} | hexdump
        echo ${{ secrets.ROOT_PASSWORD }}
        echo ${{ vars.TEST1 }}
        env

